ALTER TABLE myschema.produk ADD COLUMN stok integer;

ALTER TABLE myschema.produk RENAME COLUMN nama_produk TO nama_barang;

ALTER TABLE myschema.produk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;